### ISSUE TITLE
could you write unit test at ceedling 

### ISSUE THREAD

**Issue by amigomcu** [ryanplusplus/tiny#7]
could you write unit test at ceedling ?
how to convert cpputest to ceedling for unit test.

**Comment by ryanplusplus** [comment]
Hey @amigomcu, sorry I didn't see this until now because my notification settings were messed up for this repo. I chose to use CppUTest instead of Ceedling because that's what I'm most familiar with. It looks like Ceedling can do everything that CppUTest does, but I don't have any experience converting between the two. For now I'd like to stick with CppUTest because I don't see a strong reason to switch to Ceedling.
